name:          9seeds Engineering Best Practices
title:         9seeds Engineering Best Practices
description:   Project engineering best practices used by 9seeds.
url:           https://9seeds.github.io/
baseurl:       /Engineering-Best-Practices
author:
  name:    9seeds
  email:   sales@9seeds.com
  github:  9seeds
  twitter: 9seeds

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
encoding:      utf-8
kramdown:
  input: GFM
sass:
  sass_dir: _includes/_sass

theme: jekyll-theme-cayman